### ISSUE TITLE
Workflow error

### ISSUE THREAD

**Issue by dazWiLLiE** [MatthewWest/pass-alfred#3] opened 2016-05-06 11:49 UTC
Hi.

I get this error from Alfred 2 v2.8.4 (437), after i type "pass", space, and a letter:

```
Starting debug for 'pass'

`[ERROR:` alfred.workflow.input.scriptfilter] Code 1: 13:44:59 workflow.py:1387 DEBUG    Reading settings from /Users/Magnus/Library/Application Support/Alfred 2/Workflow Data/org.passwordstore.pass/settings.json ...
13:44:59 workflow.py:1990 ERROR    'ascii' codec can't decode byte 0xcc in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/Magnus/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6A4B388E-4F73-4359-BC6B-A3B2F79FE02B/workflow/workflow.py", line 1983, in run
    func(self)
  File "pass.py", line 140, in main
    results = wflow.filter(query, rel_paths, key=search_key_for_pw, min_score=20)
  File "/Users/Magnus/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6A4B388E-4F73-4359-BC6B-A3B2F79FE02B/workflow/workflow.py", line 1803, in filter
    value = key(item).strip()
  File "pass.py", line 16, in search_key_for_pw
    return u' '.join(elements)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 12: ordinal not in range(128)
13:44:59 workflow.py:2008 DEBUG    Workflow finished in 0.013 seconds.
```

**Comment by MatthewWest** [comment] 2016-05-13 17:44
This seems to be a problem with the workflow library which I'm using, as it parses your input. I'll try updating to the latest version of that library, and let you know if that fixes it. If not, you can report the issue here: https://github.com/deanishe/alfred-workflow/issues

Out of curiosity, what language are you typing in? The error is a Unicode parsing error, so i figure it must not be English.

**Comment by dazWiLLiE** [comment] 2016-05-13 18:04
Ah, I see. Alright, I will try it out later.

Swedish :)

**Comment by MatthewWest** [comment] 2016-05-13 18:51
I just updated to the newest version of alfred-workflow and I'm closing this provisionally. If your error keeps happening I'll see if I can reproduce it. 

Closed by https://github.com/MatthewWest/pass-alfred/commit/b68bd07423c7197c0a392325af85162adb7886ae

**Closed as completed by MatthewWest** 2016-05-13 18:51 UTC
